# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    container_name: pokedeck-db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: pokedeck-db-inspect
    ports:
      - 8080:8080
